weight_quantization:
  module_kwargs:
    classifier_name: ternary-resnet-18
    lr_scheduler_name: CosineDecayLRSched
    lr_scheduler_kwargs:
      warmup_prop: 0.05
      const_prop: 0.15
    lr: 1.e-2
    beta_1: 0.9
    beta_2: 0.999
    eps: 1.e-8
    ternary_weight_decay: 1.e-11
    full_precision_weight_decay: 1.e-4
    compile_model: true
  max_epochs: 25