weight_quantization:
  module_kwargs:
    classifier_name: binary-mlp
    classifier_kwargs:
      hidden_layer_count: 1
      hidden_layer_dim: 2048
    lr: 2.e-4
    beta_1: 0.9
    beta_2: 0.999
    eps: 1.e-8
  max_epochs: 10